---
title: "Пример RMD-ноутбука"
author: "Olga Potanina"
date: "2023-10-08"
output:
  word_document: default
---

# Описание данных

В данном примере RMD-ноутбука рассматривается датасет "Ирисы Фишера", более подробную информацию о котором можно изучить на сайте [wikipedia.org](https://ru.wikipedia.org/wiki/Ирисы_Фишера "Ирисы Фишера")

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
iris <- iris
```

В данных содержится `r nrow (iris)` наблюдений. Ниже представлены описательные статистики переменных датасета.

```{r 1, echo = FALSE}
summary (iris, digits=2)
```
# Описание данных
```{r 2}
statistics <- list(
      `Количество (есть данные)` = ~sum(!is.na(.x)) %>% as.character(),
      `Нет данных` = ~sum(is.na(.x)) %>% as.character(),
      `Ср. знач.` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", mean(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `Станд. отклон.` = ~ifelse(sum(!is.na(.x)) < 3, "Н/П*", sd(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `Медиана` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", median(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `Q1 - Q3` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", paste0(quantile(.x, 0.25, na.rm = TRUE) %>% round(2), " - ", quantile(.x, 0.75, na.rm = TRUE) %>% round(2))) %>% as.character())

library(flextable)

iris %>% 
  select ('Species', where (is.numeric)) %>% 
  group_by(Species) %>% 
  summarise(across (where(is.numeric), statistics)) %>% 
  pivot_longer (!'Species') %>% 
  separate(name, into = c("Переменная", "Статистика"), sep = "_") %>% 
  rename("Вид" = Species, "Значение" = value) %>% 
  flextable() %>% theme_box() %>%
  merge_v (c ("Вид", "Переменная")) %>% 
  align(align = "center")

```
